site_name: Veille technologique (420-1SX - Cégep de Shawinigan)
site_author: Nicolas Bourré
site_url: https://nbourre.github.io/1sh_notes_cours/

theme:
  name: material
  language: fr
  logo: https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/docs/assets/images/favicon.png
  favicon: https://raw.githubusercontent.com/squidfunk/mkdocs-material/master/docs/assets/images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    annotation: material/arrow-right-circle

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nbourre
      name: GitHub Repository
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@NicolasBourre
  generator: false

nav:
  - Accueil: index.md
  - OneNote: onenote/index.md
  - Prendre des notes avec GH : github_notes/index.md
  - Articles:
    - Les dangers du vibe coding :  articles/dangers-vibe-coding.md
    - Danger des emplois liés à l'IA : articles/AI_jobs_danger_traduction.md
    - Vibe-coding = programmeurs sans réflexion : articles/vibe_coding_gambling.md
    - Réaliser un devis de projet : devis_projet/index.md